/**
 * تعريف سمات الألوان (Themes) المتاحة في التطبيق
 * تم تحسين التباين والألوان لضمان وضوح كافة التفاصيل في كل ثيم
 */
export const THEMES = {
    corporate: {
        id: 'corporate',
        name: 'أزرق كريستالي (Professional)',
        bg: '#f8fafc',
        card: '#ffffff',
        accent: '#2563eb',
        text: '#0f172a',
        muted: '#64748b',
        border: '#e2e8f0',
        itemBg: '#fcfcfd',
        isDark: false,
        primary: 'blue',
        preview: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)'
    },
    dark: {
        id: 'dark',
        name: 'ليلي هادئ (Midnight)',
        bg: '#0f172a',
        card: '#1e293b',
        accent: '#38bdf8',
        text: '#f1f5f9',
        muted: '#94a3b8',
        border: '#334155',
        itemBg: '#1e293b',
        isDark: true,
        primary: 'sky',
        preview: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)'
    },
    emerald: {
        id: 'emerald',
        name: 'غابة الأمازون (Emerald)',
        bg: '#f0fdf4',
        card: '#ffffff',
        accent: '#059669',
        text: '#064e3b',
        muted: '#34d399',
        border: '#d1fae5',
        itemBg: '#fcfdfa',
        isDark: false,
        primary: 'emerald',
        preview: 'linear-gradient(135deg, #10b981 0%, #059669 100%)'
    },
    cyberpunk: {
        id: 'cyberpunk',
        name: 'نيون مستقبلي (Cyber)',
        bg: '#020617',
        card: '#0f172a',
        accent: '#f43f5e',
        text: '#ffffff',
        muted: '#94a3b8',
        border: '#1e293b',
        itemBg: '#111827',
        isDark: true,
        primary: 'rose',
        preview: 'linear-gradient(135deg, #f43f5e 0%, #fb7185 100%)'
    },
    luxury: {
        id: 'luxury',
        name: 'ذهبي ملكي (Luxury)',
        bg: '#fafaf9',
        card: '#ffffff',
        accent: '#b45309',
        text: '#44403c',
        muted: '#a8a29e',
        border: '#f5f5f4',
        itemBg: '#fcfcfd',
        isDark: false,
        primary: 'amber',
        preview: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)'
    },
    nordic: {
        id: 'nordic',
        name: 'ثلج الشمال (Nordic)',
        bg: '#f1f5f9',
        card: '#ffffff',
        accent: '#475569',
        text: '#1e293b',
        muted: '#94a3b8',
        border: '#e2e8f0',
        itemBg: '#fcfcfd',
        isDark: false,
        primary: 'slate',
        preview: 'linear-gradient(135deg, #94a3b8 0%, #475569 100%)'
    },
    mint: {
        id: 'mint',
        name: 'نعناع بـارد (Mint)',
        bg: '#f0fdfa',
        card: '#ffffff',
        accent: '#0d9488',
        text: '#134e4a',
        muted: '#5eead4',
        border: '#ccfbf1',
        itemBg: '#fcfdfa',
        isDark: false,
        primary: 'teal',
        preview: 'linear-gradient(135deg, #2dd4bf 0%, #0d9488 100%)'
    },
    sakura: {
        id: 'sakura',
        name: 'أزهار الكرز (Sakura)',
        bg: '#fff1f2',
        card: '#ffffff',
        accent: '#db2777',
        text: '#831843',
        muted: '#f472b6',
        border: '#ffe4e6',
        itemBg: '#fffafb',
        isDark: false,
        primary: 'pink',
        preview: 'linear-gradient(135deg, #f472b6 0%, #db2777 100%)'
    },
    deepblue: {
        id: 'deepblue',
        name: 'أعماق المحيط (Deep Ocean)',
        bg: '#0c4a6e',
        card: '#075985',
        accent: '#38bdf8',
        text: '#ffffff',
        muted: '#7dd3fc',
        border: '#0ea5e9',
        itemBg: '#085078',
        isDark: true,
        primary: 'sky',
        preview: 'linear-gradient(135deg, #0284c7 0%, #0c4a6e 100%)'
    },
    minimalist: {
        id: 'minimalist',
        name: 'بسيط جداً (Minimal)',
        bg: '#ffffff',
        card: '#ffffff',
        accent: '#000000',
        text: '#000000',
        muted: '#71717a',
        border: '#f4f4f5',
        itemBg: '#fafafa',
        isDark: false,
        primary: 'black',
        preview: 'linear-gradient(135deg, #27272a 0%, #000000 100%)'
    }
};
